services:
  - name: wellness-analyzer-api
    env: python
    type: web
    region: oregon
    plan: free
    branch: main
    # This section forces Render to use a specific, stable Python version.
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"


