
services:
  - name: wellness-analyzer-api
    env: python
    #
    # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    # THIS IS THE NEW LINE
    # We are forcing Render to use Python 3.9 for better stability.
    pythonVersion: '3.9'
    # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    #
    type: web
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

